Ссылка на датасет: https://www.kaggle.com/datasets/thuandao/bank-transactions-dataset-for-fraud-detection
датасет включает в себя транзакции с IP, банком, датой, типом и местом

In [33]:
import pandas as pd
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction import FeatureHasher
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import Pipeline

plt.style.use("fivethirtyeight")
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 12
pd.set_option('display.max_columns', None)
sb.set(font_scale=1.2)

df = pd.read_csv('./bank_transactions_data_2_augmented_clean_2.csv')

In [2]:
df.head(10)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
3,TX000004,AC00070,184.50,5/5/2023 16:32,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
4,TX000005,AC00411,13.45,10/16/2023 17:51,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40
5,TX000006,AC00393,92.15,4/3/2023 17:15,Debit,Oklahoma City,D000579,117.67.192.211,M054,ATM,18,Student,172,1,781.68
6,TX000007,AC00199,7.08,2/15/2023 16:36,Credit,Seattle,D000241,140.212.253.222,M019,ATM,37,Doctor,139,1,13316.71
7,TX000008,AC00069,171.42,5/8/2023 17:47,Credit,Indianapolis,D000500,92.214.76.157,M020,Branch,67,Retired,291,1,2796.24
8,TX000009,AC00135,106.23,3/21/2023 16:59,Credit,Detroit,D000690,24.148.92.177,M035,Branch,51,Engineer,86,1,9095.14
9,TX000010,AC00385,815.96,3/31/2023 16:06,Debit,Nashville,D000199,32.169.88.41,M007,ATM,55,Doctor,120,1,1021.88

In [3]:
df.tail(10)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
49990,TX049991,AC00010,283.69,8/20/2020,Debit,Denver,D000312,24.148.92.177,M069,Branch,25,Student,269,1,225.53
49991,TX049992,AC00338,91.36,8/28/2020,Debit,Milwaukee,D000353,49.29.37.185,M056,Branch,58,Engineer,77,1,2618.10
49992,TX049993,AC00185,170.53,9/12/2025,Debit,Baltimore,D000371,81.67.222.238,M031,ATM,33,Doctor,17,1,10724.95
49993,TX049994,AC00144,509.23,2/22/2025,Debit,Kansas City,D000100,73.54.203.165,M038,Online,22,Student,82,1,1806.00
49994,TX049995,AC00275,352.83,7/13/2023,Debit,Detroit,D000196,163.58.140.206,M038,ATM,43,Engineer,37,1,7234.15
49995,TX049996,AC00314,69.23,1/28/2025,Debit,Las Vegas,D000546,44.67.137.125,M097,Online,69,Doctor,69,1,6020.29
49996,TX049997,AC00370,514.53,1/23/2022,Debit,Houston,D000589,140.212.253.222,M061,ATM,46,Engineer,143,1,6371.51
49997,TX049998,AC00277,118.39,11/8/2022,Debit,Omaha,D000217,152.140.239.181,M029,Online,33,Doctor,296,1,749.34
49998,TX049999,AC00007,446.99,4/20/2025,Debit,Las Vegas,D000327,131.41.45.13,M082,ATM,58,Doctor,11,1,10915.11
49999,TX050000,AC00427,84.82,11/19/2020,Debit,Dallas,D000355,192.163.114.167,M078,Branch,31,Doctor,23,1,842.56

In [4]:
display(df.shape)

(50000, 15)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  str
 1   AccountID            50000 non-null  str
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  str
 4   TransactionType      50000 non-null  str
 5   Location             50000 non-null  str
 6   DeviceID             50000 non-null  str
 7   IP Address           50000 non-null  str
 8   MerchantID           50000 non-null  str
 9   Channel              50000 non-null  str
 10  CustomerAge          50000 non-null  int64
 11  CustomerOccupation   50000 non-null  str
 12  TransactionDuration  50000 non-null  int64
 13  LoginAttempts        50000 non-null  int64
 14  AccountBalance       50000 non-null  float64
dtypes: float64(2), int64(3), str(10)
memory usage: 5.7 MB

In [6]:
display(df.describe())

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,297.872214,44.647600,118.965320,1.12684,5122.738301
std,292.818888,17.800293,70.000681,0.60936,3904.266887
min,0.240000,18.000000,10.000000,1.00000,101.250000
25%,82.897500,27.000000,63.000000,1.00000,1508.720000
50%,209.355000,45.000000,111.000000,1.00000,4735.410000
75%,409.625000,59.000000,161.000000,1.00000,7713.670000
max,2060.590000,80.000000,300.000000,5.00000,14977.990000

In [7]:
display(df.describe(include="str"))

,TransactionID,AccountID,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerOccupation
count,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000
unique,50000,495,6373,2,43,681,592,100,3,4
top,TX000001,AC00363,6/12/2021,Debit,Fort Worth,D000548,200.136.146.93,M026,Branch,Student
freq,1,249,35,38747,1396,196,261,940,17278,13059

In [8]:
print("ПРОПУЩЕННЫЕ ЗНАЧЕНИЯ:\n")
missing_data = pd.DataFrame({
    'Тип_данных': df.dtypes,
    'Пропусков': df.isnull().sum(),
    '% пропусков': (df.isnull().sum() / len(df) * 100).round(2)
})
missing_data = missing_data[missing_data['Пропусков'] > 0].sort_values('Пропусков', ascending=False)

ПРОПУЩЕННЫЕ ЗНАЧЕНИЯ:

In [9]:
numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

basic_stats = []
for col in numeric_cols:
    col_data = df[col].dropna()
    
    mode_values = col_data.mode()
    
    basic_stats.append({
        'Признак': col,
        'Минимум': col_data.min(),
        'Максимум': col_data.max(),
        'Среднее (mean)': col_data.mean(),
        'Медиана (median)': col_data.median(),
        'Мода (mode)': mode_values[0],
    })

basic_df = pd.DataFrame(basic_stats).round(2)
display(basic_df)

/tmp/ipykernel_15445/4067922813.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object', 'category']).columns

,Признак,Минимум,Максимум,Среднее (mean),Медиана (median),Мода (mode)
0,TransactionAmount,0.24,2060.59,297.87,209.36,0.26
1,CustomerAge,18.00,80.00,44.65,45.00,27.00
2,TransactionDuration,10.00,300.00,118.97,111.00,63.00
3,LoginAttempts,1.00,5.00,1.13,1.00,1.00
4,AccountBalance,101.25,14977.99,5122.74,4735.41,1400.04

In [10]:
percentiles = [5, 25, 50, 75, 95]
percentile_data = []

for col in numeric_cols:
    col_data = df[col].dropna()
    percentiles_dict = {'Признак': col}
    
    for p in percentiles:
        percentiles_dict[f'{p}%'] = np.percentile(col_data, p)
    
    percentile_data.append(percentiles_dict)

percentile_df = pd.DataFrame(percentile_data).round(2)
display(percentile_df)

               Признак      5%      25%      50%      75%       95%
0    TransactionAmount   15.95    82.90   209.36   409.62    884.55
1          CustomerAge   20.00    27.00    45.00    59.00     74.00
2  TransactionDuration   24.00    63.00   111.00   161.00    265.00
3        LoginAttempts    1.00     1.00     1.00     1.00      1.00
4       AccountBalance  383.58  1508.72  4735.41  7713.67  12896.68

In [11]:
advanced_stats = []
for col in numeric_cols:
    col_data = df[col].dropna()
    
    advanced_stats.append({
        'Признак': col,
        'Дисперсия (variance)': col_data.var(),
        'Асимметрия (skewness)': col_data.skew(),
        'Эксцесс (kurtois)': col_data.kurtosis(),
    })

advanced_df = pd.DataFrame(advanced_stats).round(2)
display(advanced_df)

,Признак,Дисперсия (variance),Асимметрия (skewness),Эксцесс (kurtois)
0,TransactionAmount,85742.90,1.77,3.81
1,CustomerAge,316.85,0.15,-1.23
2,TransactionDuration,4900.10,0.62,-0.24
3,LoginAttempts,0.37,5.12,26.08
4,AccountBalance,15243299.93,0.59,-0.58

Судя по этим параметрам: 
1)Разброс в количестве денег в транзакциях большой, много малых хначений, больше редких, и пик очень острый
2)Возраст не так сильно разбросан, почти нормальное распределение, плоский пик
3)Длительность транзакции варьируется, чуть больше малых значений, около-нормальный пик
4)Количество попыток ввода почти везде равняется среднему(1), очень много малых значений, очень отсрый пик
5)Огромный разброс баланса, немного больше малых значений, пологий пик

In [12]:
categories = []
for col in categorical_cols:
    col_data = df[col].unique()
    categories.append({
        'Признак' : col, 
        'Количество' : len(col_data)
    })
categories_df = pd.DataFrame(categories)
display(categories_df)

              Признак  Количество
0       TransactionID       50000
1           AccountID         495
2     TransactionDate        6373
3     TransactionType           2
4            Location          43
5            DeviceID         681
6          IP Address         592
7          MerchantID         100
8             Channel           3
9  CustomerOccupation           4

In [37]:
low_count_categories_list = categories_df.iloc[:, 1]
low_count_rows = low_count_categories_list < 10
low_count_rows = low_count_categories_list[low_count_rows].index.tolist()
high_count_categories_df = categories_df.drop(index=low_count_rows)
low_count_categories_df = categories_df.loc[categories_df.index.isin(low_count_rows)]

low_count_mask = df.columns.isin(low_count_categories_df.iloc[:, 0].tolist())
high_count_mask = df.columns.isin(high_count_categories_df.iloc[:, 0].tolist())

# display(low_count_mask)
# display(high_count_mask)

In [61]:
onehot_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
low_cardinality_encoded = onehot_encoder.fit_transform(df.loc[:, low_count_mask])

In [64]:
high_count_dicts = df.loc[:,high_count_mask].to_dict('records')
hasher = FeatureHasher(n_features=6, input_type='dict', alternate_sign=False)
high_cardinality_encoded = hasher.fit_transform(high_count_dicts).toarray()

numeric_data = df[numeric_cols].values

# display(low_cardinality_encoded)
display(high_cardinality_encoded)
# display(numeric_data)


df_encoded = np.hstack([low_cardinality_encoded, 
                        high_cardinality_encoded, 
                        numeric_data])
df_encoded = pd.DataFrame(df_encoded)

display(df_encoded)
display(df)

array([[0., 1., 2., 2., 2., 0.],
       [0., 4., 0., 0., 2., 1.],
       [0., 1., 0., 1., 1., 4.],
       ...,
       [0., 0., 1., 2., 2., 2.],
       [2., 1., 0., 1., 1., 2.],
       [2., 0., 1., 0., 4., 0.]], shape=(50000, 6))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,2.0,0.0,14.09,70.0,81.0,1.0,5112.21
1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,1.0,376.24,68.0,141.0,1.0,13758.91
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,4.0,126.29,19.0,56.0,1.0,1122.35
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,3.0,1.0,184.50,26.0,25.0,1.0,8569.06
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,2.0,1.0,2.0,0.0,13.45,26.0,198.0,1.0,7429.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0,2.0,69.23,69.0,69.0,1.0,6020.29
49996,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0,0.0,514.53,46.0,143.0,1.0,6371.51
49997,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,2.0,118.39,33.0,296.0,1.0,749.34
49998,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,1.0,2.0,446.99,58.0,11.0,1.0,10915.11
49999,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,4.0,0.0,84.82,31.0,23.0,1.0,842.56

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
3,TX000004,AC00070,184.50,5/5/2023 16:32,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
4,TX000005,AC00411,13.45,10/16/2023 17:51,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,TX049996,AC00314,69.23,1/28/2025,Debit,Las Vegas,D000546,44.67.137.125,M097,Online,69,Doctor,69,1,6020.29
49996,TX049997,AC00370,514.53,1/23/2022,Debit,Houston,D000589,140.212.253.222,M061,ATM,46,Engineer,143,1,6371.51
49997,TX049998,AC00277,118.39,11/8/2022,Debit,Omaha,D000217,152.140.239.181,M029,Online,33,Doctor,296,1,749.34
49998,TX049999,AC00007,446.99,4/20/2025,Debit,Las Vegas,D000327,131.41.45.13,M082,ATM,58,Doctor,11,1,10915.11
49999,TX050000,AC00427,84.82,11/19/2020,Debit,Dallas,D000355,192.163.114.167,M078,Branch,31,Doctor,23,1,842.56